### ISSUE TITLE
A few HTML and accessibility/usability errors on send.firefox.com

### ISSUE THREAD

**Issue by pdehaan** [mozilla/send#139]
Ref: https://github.com/mozilla/send/issues/139#issuecomment-320333492

- [x] The “width” attribute on the “th” element is obsolete. Use CSS instead #436
- [x] 'x-ua-compatible' header was not specified #437
- [x] Text of buttons and links should not be repeated in the image alternative #438
- [x] `target="_blank"` is missing 'rel' values 'noopener', 'noreferrer' #439
- [x] An “img” element must have an “alt” attribute, except under certain conditions #440
- [x] Bad value “true” for attribute “hidden” on element “div” #441
- [x] Links must have discernible text #442
- [x] Elements must have sufficient color contrast #443

**Comment by pdehaan** [comment]
Nothing too dramatic showing up in [**a11y**](https://github.com/addyosmani/a11y) results:

```sh
> npm i a11y -D
> $(npm bin)/a11y https://fileshare.stage.mozaws.net/

  ✖ Controls and media elements should have labels

  #link


  ✔ This element does not support ARIA roles, states and properties
  ✔ Any ID referred to via an IDREF must be unique in the DOM
```

I think it's complaining about this DOM element `<input id="link" type="url" value="" readonly/>` and it's lack of an associated `<label>` tag.

--- 

I'm not aware of any other ESLint-y a11y linters, apart from https://www.npmjs.com/package/eslint-plugin-jsx-a11y. Although that one (while super awesome) relies on JSX, which may mean some front end rewriting and possibly converting to JSX/React.

**Comment by pdehaan** [comment]
Most of these should be fixed with the new design, but I can re-run the scanner after the new design lands and make sure we pass a11y and basic HTML linting.

**Comment by pdehaan** [comment]
Latest results:

```
npm run sonar https://send.dev.mozaws.net/

> sonar-test@1.0.0 sonar /Users/pdehaan/dev/tmp/del/sonar-test
> sonar "https://send.dev.mozaws.net/"

✖ Finishing...
https://send.dev.mozaws.net/
                  Error  'x-ua-compatible' header was not specified                                                                                                                highest-available-document-mode
line 14   col 3   Error  Bad value “localization” for attribute “rel” on element “link”: The string “localization” is not a registered keyword.                                    html-checker
line 14   col 3   Error  Bad value “/locales/{locale}/send.ftl” for attribute “href” on element “link”: Illegal character in path segment: “{” is not allowed.                     html-checker
line 21   col 7   Error  Text of buttons and links should not be repeated in the image alternative                                                                                 axe
line 25   col 19  Error  '<a href="https://testpilot.firefox.com" target="_blank">Firefox Test Pilot</a>' is missing 'rel' values 'noopener', 'noreferrer'                         disown-opener
line 47   col 26  Error  An “img” element must have an “alt” attribute, except under certain conditions. For details, consult guidance on providing text alternatives for images.  html-checker
line 49   col 7   Error  Elements must have sufficient color contrast                                                                                                              axe
line 62   col 46  Error  The “width” attribute on the “th” element is obsolete. Use CSS instead.                                                                                   html-checker
line 63   col 60  Error  The “width” attribute on the “th” element is obsolete. Use CSS instead.                                                                                   html-checker
line 64   col 60  Error  The “width” attribute on the “th” element is obsolete. Use CSS instead.                                                                                   html-checker
line 65   col 62  Error  The “width” attribute on the “th” element is obsolete. Use CSS instead.                                                                                   html-checker
line 75   col 1   Error  Bad value “true” for attribute “hidden” on element “div”.                                                                                                 html-checker
line 93   col 1   Error  Bad value “true” for attribute “hidden” on element “div”.                                                                                                 html-checker
line 106  col 1   Error  Bad value “true” for attribute “hidden” on element “div”.                                                                                                 html-checker
line 109  col 3   Error  An “img” element must have an “alt” attribute, except under certain conditions. For details, consult guidance on providing text alternatives for images.  html-checker
line 112  col 7   Error  Links must have discernible text                                                                                                                          axe
line 112  col 17  Error  '<a href="https://www.mozilla.org" target="_blank … illa-logo" src="/resources/mozilla-logo.svg"></a>' is missing 'rel' values 'noopener', 'noreferrer'   disown-opener
line 112  col 57  Error  Images must have alternate text                                                                                                                           axe
line 113  col 17  Error  '<a href="https://www.mozilla.org/about/legal" da … 0n-id="footerLinkLegal" target="_blank">Legal</a>' is missing 'rel' values 'noopener', 'noreferrer'   disown-opener
line 114  col 17  Error  '<a href="https://testpilot.firefox.com/about" da … erLinkAbout" target="_blank">About Test Pilot</a>' is missing 'rel' values 'noopener', 'noreferrer'   disown-opener
line 116  col 57  Error  An “img” element must have an “alt” attribute, except under certain conditions. For details, consult guidance on providing text alternatives for images.  html-checker
line 117  col 17  Error  '<a href="https://www.mozilla.org/privacy/website … d="footerLinkCookies" target="_blank">Cookies</a>' is missing 'rel' values 'noopener', 'noreferrer'   disown-opener
line 120  col 7   Error  Links must have discernible text                                                                                                                          axe
line 120  col 91  Error  Images must have alternate text                                                                                                                           axe
line 121  col 7   Error  Links must have discernible text                                                                                                                          axe
line 121  col 91  Error  Images must have alternate text                                                                                                                           axe
line 124  col 91  Error  An “img” element must have an “alt” attribute, except under certain conditions. For details, consult guidance on providing text alternatives for images.  html-checker
line 125  col 91  Error  An “img” element must have an “alt” attribute, except under certain conditions. For details, consult guidance on providing text alternatives for images.  html-checker
✖ Found 28 errors and 0 warnings

✖ Found a total of 28 errors and 0 warnings
Exit code: 1
```

**Comment by TheAdnan** [comment]
Hi, are these issues still open, I'd like to help :)

**Comment by vladikoff** [comment]
@TheAdnan Cool! please !

**Comment by ajomadlabs** [comment]
Hi, Can I also help in fixing these

**Comment by brainlulz** [comment]
@pdehaan Can you update your list ? All issues are closed.
