### ISSUE TITLE
Security Checklist

### ISSUE THREAD

**Issue by jvehent** [mozilla/send#202]
Risk Management
---------------
* [x] The service must have performed a Rapid Risk Assessment and have a Risk Record bug (**SVC-RRA**).
 
Infrastructure rules
--------------------
 
* [x] Access and application logs must be archived for a minimum of 90 days
* [x] Use [Modern](https://wiki.mozilla.org/Security/Server_Side_TLS#Modern_compatibility) or [Intermediate](https://wiki.mozilla.org/Security/Server_Side_TLS#Intermediate_compatibility) TLS (**INFRA-TLS**)
* [x] Set HSTS to 31536000 (1 year) (**INFRA-HSTS**)
  * `strict-transport-security: max-age=31536000`
* [x] Set HPKP to 5184000 (60 days) (**INFRA-HPKP**)
  * `Public-Key-Pins: max-age=5184000; pin-sha256="WoiWRyIOVNa9ihaBciRSC7XHjliYS9VwUGOIud4PB18="; pin-sha256="r/mIkG3eEpVdm+u/ko/cwxzOMo1bk4TyHIlByibiA5E="; pin-sha256="YLh1dUR9y6Kja30RrAn7JKnbQG/uEtLMkBgFF2Fuihg="; pin-sha256="sRHdihwgkaib1P1gxX8HFszlD+7/gTfNvuAybgLPNis=";`
    * Start with max-age set to 5 minutes (`max-age=300`) and increase progressively
    * The first two pins are for Digicert EV and DV roots, the last two are for Let's Encrypt X3 and X4 intermediates (LE is only used for backup)
  * [x] If the service is not hosted under `services.mozilla.com`, it must be manually added to [Firefox's preloaded pins](https://dxr.mozilla.org/mozilla-central/source/security/manager/tools/PreloadedHPKPins.json#184).
* If service has an admin panels, it must:
  * [x] only be available behind Mozilla VPN (which provides MFA) (**INFRA-ADMINVPN**)
  * [x] require LDAP authentication (**INFRA-ADMINLDAP**)
  * [x] enforce a two-man rule on sensitive changes (**INFRA-2MANRULE**)
 
Coding rules
------------
 
The following rules apply to all web applications: api and websites.
 
* [x] Sign all release tags, and maybe commits as well (**APP-COMMITSIG**)
  * Developers should [configure git to sign all tags](http://micropipes.com/blog//2016/08/31/signing-your-commits-on-github-with-a-gpg-key/) and upload their PGP fingerprint to https://login.mozilla.com
  * The signature verification will eventually become a requirement to shipping a release to staging & prod: the tag being deployed in the pipeline must have a matching tag in git signed by a project owner. This control is designed to reduce the risk of a 3rd party GitHub integration from compromising our source code.
* [x] Publish detailed logs in [mozlog](https://github.com/mozilla-services/Dockerflow/blob/master/docs/mozlog.md) format (**APP-MOZLOG**)
  * Business logic must be logged with app specific codes (errno)
  * Access control failures must be logged at WARN level
* [x] Must have a CSP with (**APP-CSP**)
  * [x] a report-uri pointing to the service's own `/__cspreport__` endpoint
  * [x] web APIs should set `default-src` to `none`, disallowing all content rendering
  * [x] if default-src is not `self`, frame-src and object-src should be `none` or only allow specific origins
  * [x] no use of unsafe-inline or unsafe-eval
* [x] User data must be escaped for the right context prior to reflecting it (**APP-ESCAPE**)
* [x] Web APIs must set a non-HTML content-type on all responses, including 300s, 400s and 500s (**APP-NOHTML**)
* [x] <strike>All SQL queries must be parameterized, not concatenated (**APP-SQL**)</strike>
* [x] Apply sensible limits to user inputs, see [input validation](https://wiki.mozilla.org/WebAppSec/Secure_Coding_Guidelines#Input_Validation) (**APP-INPUTVAL**)
* [x] When managing permissions, make sure access controls are enforced server-side (**APP-ACL**)
* [x] <strike>Set the Secure and HTTPOnly flags on [Cookies](https://wiki.mozilla.org/Security/Guidelines/Web_Security#Cookies), and use sensible Expiration (**APP-SECCOOKIE**)</strike>
* Keep 3rd-party libraries up to date (**APP-DEPS**)
  * [x] Use [NSP](https://nodesecurity.io/) or [GreenKeeper](https://greenkeeper.io/Greenkeeper) for NodeJS applications
  * [x] <strike>For Python applications, enable pyup security updates:</strike>
    * Add a pyup config to your repo (example config: https://github.com/mozilla-services/antenna/blob/master/.pyup.yml)
    * Add https://github.com/mozsvcpyup as a collaborator to your repo
    * Notify secops@mozilla.com to enable the integration in pyup
    * Consider using pip --outdated or [requires.io](https://requires.io/) too
* [x] If handling cryptographic keys, must have a mechanism to handle quarterly key rotations (**APP-KEYROT**)
  * Keys used to sign sessions don't need a rotation mechanism if destroying all sessions is acceptable in case of emergency.
* [x] <strike>Applications must use accounts with limited GRANTS when connecting to databases (**APP-DBPRIV**)</strike>
  * In particular, applications **must not use admin or owner accounts**, to decrease the impact of a sql injection vulnerability.
* [x] fork, exec, subprocess, child_process, etc. calls passing user input to a binary should be [sandboxed](https://github.com/mozilla-services/foxsec/blob/master/docs/sandbox.md)

(edit) - crossed out N/A items

**Comment by jvehent** [comment]
The base setup already gets a B+ on [the observatory](https://observatory.mozilla.org/analyze.html?host=send.stage.mozaws.net) so I checked the sections that already pass. Please go through the unchecked items, preferably before going live.

**Comment by pdehaan** [comment]
27/27... @jvehent @clouserw Any objections to us closing this?

**Comment by wresuolc** [comment]
I'm happy if @jvehent is happy

**Comment by jvehent** [comment]
No objection. Thanks for going through it!
